spring.application.name=pantry-tracker

# App Security (loaded from environment)
pantry.security.admin.username=${PANTRY_ADMIN_USER}
pantry.security.admin.password=${PANTRY_ADMIN_PASS}

# File-based H2 Database
spring.datasource.url=jdbc:h2:file:./data/pantrydb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Preserve existing schema & data across restarts
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console